services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: development
      MINIO_ROOT_PASSWORD: dev-pass
    volumes:
      - ./data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"